version: 0.2

env:
  # As we are building the code and generating jOOQ our dev DB is the source of truth.
  # Gradle is checking for the ENV var regardless of the value but if there is a value will go to the dev DB
  # In the future the code won't be build and the jar will be pulled from CodeArtifact
  variables:
    ENV: prod
  parameter-store:
    REACT_APP_STRIPE_PUBLISHABLE_KEY: "/config/xtages_console_prod/xtages.console.stripe.publicApiKey"

phases:
  pre_build:
    commands:
      - nohup /usr/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 606626603369.dkr.ecr.us-east-1.amazonaws.com
      - source ~/.bashrc
  build:
    commands:
      - cd backend
      - export DATE=`date '+%Y%m%d%H%M'` && export GIT_HASH=`git rev-parse --short HEAD`
      - export TAG=$DATE-$GIT_HASH
      - export REACT_APP_RELEASE_TAG=$TAG
      # not running gradle build to save money in CodeBuild
      - gradle --stacktrace bootJar
      - docker build --build-arg ENV=prod -t 606626603369.dkr.ecr.us-east-1.amazonaws.com/xtages-console:$TAG .
      - docker push 606626603369.dkr.ecr.us-east-1.amazonaws.com/xtages-console:$TAG
      - export TF_VAR_TAG=$TAG
      - cd ../deploy/terraform && terraform init && terraform plan && terraform apply -auto-approve
